### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bdon** [s3rgiosan/utm-utilities#2]
Hi, thanks for this library. Can you add a license to the repository?

http://choosealicense.com/

If no preferences I think MIT is usually a good choice

**Comment by s3rgiosan** [comment]
Hi @bdon, a license was added. https://github.com/s3rgiosan/utm-utilities/commit/e3d3772e007582824888e9d867512f3bc24626a5

**Comment by bdon** [comment]
Thank you! :+1:
